### PR TITLE
Forgot to fix the sidebar when doing #41

### PR DESCRIPTION
**Pull request by uhidontkno**
This PR fixes the 404 for the Cloudflare Workers guide

### CODE REVIEW

**Review by FreeAoi — APPROVED** [review]

**Review by MARCROCK22 — APPROVED** [review]

**Comment by uhidontkno** [comment]
unsure if the people that merged #41 even saw my mistake lol

**Comment by EvilG-MC** [comment]
technically, you should have tested it before doing a PR

**Comment by FreeAoi** [comment]
> unsure if the people that merged #41 even saw my mistake lol

I didn't test it tbh only check files changes

**Comment by EvilG-MC** [comment]
> > unsure if the people that merged #41 even saw my mistake lol
> 
> I didn't test it tbh only check files changes

nuv

**Comment by uhidontkno** [comment]
> technically, you should have tested it before doing a PR

~~yes but i couldn't view vercel's pr deployments~~ i just didnt look :skull:

**Pull request merged**
